platform: add wirless powershare
whatawurst/android_device_samsung_universal9820-common pull request #113
Opened 2020-04-11 12:05 UTC by Linux-4

Seems to work fine, please test before merging

2020-04-11 12:19 UTC, cryptomilk commented
Can you explain what this is and how it works?

2020-04-11 12:21 UTC, Linux-4 commented
See: https://www.samsung.com/de/support/mobile-devices/galaxy-s10-wireless-powershare/ This adds Support for wireless powershare on lineageos (like on ivanmeler's LOS). By writing 0/1 to /sys/class/power_supply/battery/wc_tx_en wireless powershare is disabled/enabled. It also adds a custom QS Tile to toggle wireless power share.

2020-04-11 12:28 UTC, cryptomilk commented
Where do you have the implementation from?

2020-04-11 12:29 UTC, cryptomilk commented on config/init/init.exynos9820.rc
> +import /vendor/etc/init/init.exynos9820.powershare.rc
Please put the init also in `/vendor/etc/init/hw/`

2020-04-11 12:30 UTC, Linux-4 commented
I used strace to see what ivanmelers proprietary /system/bin/powersharedaemon does ... And saw it writing to /sys/class/power_supply/battery/wc_tx_en

2020-04-11 12:43 UTC, cryptomilk commented
I mean the quick setting tile code :-)

2020-04-11 12:50 UTC, Linux-4 commented
Looked up how to make custom quick settings tile (e.g [here](https://developer.android.com/reference/android/service/quicksettings/TileService) but additionally looked into the decompiled apk found on ivanmeler's LOS.

2020-04-11 14:29 UTC, cryptomilk commented
I dunno when I can test it. However the priority is to find the performance bug.

2020-04-11 19:39 UTC, derfelot commented
pretty cool feature. not sure i have a device to test this though.

2020-04-12 05:47 UTC, cryptomilk commented
I think this needs to be extened. For example it should be greyed out/not selectable if the power saver is turned on.

See:
https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/271613

Could you extend it please?

2020-04-12 05:52 UTC, cryptomilk commented
According to the linked video it needs to be above 30% battery. So I guess we need to check the battery level before turning on.

2020-04-12 05:52 UTC, cryptomilk requested changes
Please add some saftey guards :-)

2020-04-12 13:30 UTC, Linux-4 commented
> I think this needs to be extened. For example it should be greyed out/not selectable if the battery saver is turned on.
> 
> See:
> https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/271613
> 
> Could you extend it please?

That's not as easy as it would be when the QS tile would be integrated into frameworks/base, will take some time to find out how to implement it without framework modifications.

2020-04-12 15:00 UTC, cryptomilk commented
There is `/sys/class/power_supply/battery/wc_tx_stop_capacity` which tells you at how many % it should stop charging I guess

2020-04-12 15:05 UTC, cryptomilk commented
Then there is

```
WIRELESS_POWER_SHARING_SYSFS_EXTERNEL_EVENT_PATH = "/sys/class/power_supply/battery/ext_event";
```

 which takes an integer, but I'm not sure what this triggers.

2020-04-15 08:37 UTC, Linux-4 commented
Now it should be disabled when you enable powersave, and when battery < 30%, but it seems to have some problems with SELinux as it can't read/set system props with selinux enforcing, can you help?

2020-04-15 12:22 UTC, Linux-4 commented
wireless powershare is now working with selinux but the app still cant get the sys.powershare prop, set_prop(platform_app, vendor_powershare_prop) produces a neverallow error.

2020-04-15 18:12 UTC, Linux-4 commented
This needs to be implemented in LineageOS upstream to get it working with selinux enforcing.

2020-04-15 18:12 UTC, closed without merging